# Generated by Django 4.0.6 on 2022-12-27 15:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 27, 15, 33, 54, 791923, tzinfo=utc)),
        ),
    ]
