# Generated by Django 4.0.6 on 2022-12-27 15:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 27, 15, 34, 3, 184540, tzinfo=utc)),
        ),
    ]
